name: linter-check

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Linter check
        run: make lint
