name: linter-check

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
    - name:  Install dependencies
        run: make install

      - name: Linter check
        run: make lint
